### ISSUE TITLE
Please fix the code [explanation in content]

### ISSUE THREAD

**Issue by Prof-Bloodstone** [JoelGodOfwar/MoreMobHeads#4]
There's so many things wrong.

Why are you doing network requests on main thread? Why do you do them for each player join - even if the check is disabled and player is not op?

Why do you need to know the version of plugin on my server and my seed?

I'd love to use this plugin - but it is a big performance and potentially security issue rn, and I'd prefer not to rewrite it myself.

**Comment by JoelGodOfwar** [comment]
Which version of the plugin are you using?
Since 1.14_1.0.9
MMH only checks for updates on the enable, and notifies players with permission moremobheads.showUpdateAvailable which is default OP.
The plugin does not check for updates if auto_update_check is false.
Nothing in MMH checks your seed, or the version of any other plugin, in any version of the plugin.

Feel free to join my discord server https://discord.gg/Bh5YDRC if you'd like to present proof of any issues.
